### ISSUE TITLE
JUnit3 vs JUnit4

### ISSUE THREAD

**Issue by snowpong** [awslabs/aws-device-farm-sample-app-for-android#5]
Hi there,

Looking at your Espresso testcases you are using ActivityInstrumentationTestCase2 which I believe requires, or is at least tightly coupled to, JUnit3.

Now, the guys behind the Android Testing Support Library has released their own template project called the Android Testing Blueprint (ATBP) - https://github.com/googlesamples/android-testing-templates/tree/master/AndroidTestingBlueprint - where they use Junit4 and instead of ActivityInstrumentationTestCase2 they use ActivityTestRule and AndroidJUnit4.

Do you support JUnit4 and the above classes, or are we stuck with JUnit3 and ActivityInstrumentationTestCase2?

**Comment by danielgomezrico** [comment]
+1 for automatic recognition of junit4 test cases.

```
Hello,

We support JUnit 3 and JUnit4 execution, but we will not automatically discover test classes/methods within your uploaded test packages based solely on JUnit4 annotations.

I've summarized how instrumentation test discoverability works in greater detail here.

If you have any additional questions/issues or are still having test discoverability issues using the JUnit3 naming convention, please post or PM a link to a run that encountered the issue and we can investigate further.

Hope that helps!

Best,
Andrew @ AWS Device Farm

Edited by: Hawker@AWS on Aug 14, 2015 4:03 PM
```
from:
https://forums.aws.amazon.com/thread.jspa?threadID=196133

**Comment by nikhil-dabhade** [comment]
Please refer to https://forums.aws.amazon.com/ann.jspa?annID=4079
We now support JUnit 4.
Closing this issue
